export const ROLES = {
  ADMIN: 'ROLE_ADMIN',
  DOCTOR: 'ROLE_DOCTOR',
  RECEPTIONIST: 'ROLE_RECEPTIONIST',
  PHARMACIST: 'ROLE_PHARMACIST',
  CASHIER: 'ROLE_CASHIER',
  PATIENT: 'ROLE_PATIENT',
} as const;

export const ROLE_NAMES = {
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  RECEPTIONIST: 'RECEPTIONIST',
  PHARMACIST: 'PHARMACIST',
  CASHIER: 'CASHIER',
} as const;
